name: Check for Spammy Comments

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write

jobs:
  comment-filter:
    runs-on: ubuntu-latest
    steps:
    - name: Comment filter
      uses: DecimalTurn/Comment-Filter@dev
      with:
        exclude-contributors: 'true'
